name: Test application

on:
    pull_request:
    push:
        branches:
            - '[0-9]+.x'
            - '[0-9]+.[0-9]+'

jobs:
    test:
        name: 'PHP ${{ matrix.php-version }} (${{ matrix.dependency-versions }})'
        runs-on: ubuntu-latest

        env:
            DATABASE_URL: mysql://root:root@127.0.0.1:3306/su_headless_test?serverVersion=5.7
            DATABASE_CHARSET: utf8mb4
            DATABASE_COLLATE: utf8mb4_unicode_ci

        strategy:
            fail-fast: false
            matrix:
                include:
                    - php-version: '7.3'
                      coverage: false
                      dependency-versions: 'lowest'
                      tools: 'composer:v2'
                      env:
                          SYMFONY_DEPRECATIONS_HELPER: disabled

                    - php-version: '7.4'
                      coverage: true
                      dependency-versions: 'highest'
                      tools: 'composer:v2'
                      env:
                          SYMFONY_DEPRECATIONS_HELPER: weak

                    - php-version: '8.0'
                      coverage: false
                      dependency-versions: 'highest'
                      tools: 'composer:v2'
                      env:
                          SYMFONY_DEPRECATIONS_HELPER: weak

                    - php-version: '8.1'
                      coverage: false
                      dependency-versions: 'highest'
                      tools: 'composer:v2'
                      env:
                          SYMFONY_DEPRECATIONS_HELPER: weak

                    - php-version: '8.2'
                      coverage: false
                      dependency-versions: 'highest'
                      tools: 'composer:v2'
                      env:
                          SYMFONY_DEPRECATIONS_HELPER: weak

                    - php-version: '8.3'
                      coverage: false
                      dependency-versions: 'highest'
                      tools: 'composer:v2'
                      env:
                          SYMFONY_DEPRECATIONS_HELPER: weak

        services:
            mysql:
                image: mysql:5.7
                env:
                    MYSQL_ROOT_PASSWORD: root
                ports:
                    - 3306:3306
                options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=5

        steps:
            - name: Checkout project
              uses: actions/checkout@v4

            - name: Install and configure PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php-version }}
                  extensions: ctype, iconv, mysql
                  coverage: pcov
                  tools: ${{ matrix.tools }}

            - name: Remove not required test tooling
              run: composer remove "*php-cs-fixer*" "*phpstan*" --no-update --dev

            - name: Install composer dependencies
              uses: ramsey/composer-install@v3
              with:
                  dependency-versions: ${{ matrix.dependency-versions }}
                  composer-options: ${{ matrix.composer-options }}

            - name: Bootstrap test environment
              run: composer bootstrap-test-environment

            - name: Execute unit test cases
              run: composer test -- Tests/Unit --coverage-php var/coverage.php --coverage-html coverage-report --log-junit var/junit.xml

            - name: Execute functional test cases
              run: composer test -- Tests/Functional --log-junit var/junit.xml

            - name: Check code coverage
              if: ${{ matrix.coverage }}
              run: php vendor/bin/code-coverage-checker "var/coverage.php" "line" "95" "Content"

    lint:
        name: 'PHP Lint'
        runs-on: ubuntu-latest

        env:
            DATABASE_URL: mysql://root:root@127.0.0.1:3306/su_headless_test?serverVersion=5.7
            DATABASE_CHARSET: utf8mb4
            DATABASE_COLLATE: utf8mb4_unicode_ci

        steps:
            - name: Checkout project
              uses: actions/checkout@v4

            - name: Install and configure PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: 8.3
                  extensions: ctype, iconv, mysql
                  tools: highest

            - name: Install composer dependencies
              uses: ramsey/composer-install@v3
              with:
                  dependency-versions: highest

            - name: Lint code
              run: composer lint
